### ISSUE TITLE
Style of lines

### ISSUE THREAD

**Issue by Joefva** [SebastianBocquet/pygtc#30] opened 2022-02-16 05:50 UTC
Hello, small thing really, but when changing the style of the lines with "truthLineStyles" in plotGTC(), the style changes on the plot but not in the legend. It would be practical to have the two agreeing.

**Comment by FaustinCarter** [comment] 2022-03-12 22:57
This does seem like a totally reasonable request. We'd certainly welcome a pull request if you want to take a stab at it! Can't promise any kind of quick turnaround at the moment, but will try to address.

**Comment by SebastianBocquet** [comment] 2022-03-30 13:32
Thanks for pointing out the bug! The linestyle in the legend pointed to the defaults instead of the actual truthLineStyles.

@FaustinCarter You have a PR that's been pending forever. Do you want to merge this bugfix into your PR and get it done?

**Comment by SebastianBocquet** [comment] 2022-04-05 10:15
Hi @Joefva the issue is resolved with #31. The latest version 0.4.1 should work as intended.

**Closed by SebastianBocquet** 2022-04-05 10:15 UTC
